    'calc.gold.title': 'Gold calculator',
    'calc.silver.title': 'Silver calculator',
    'calc.zakat.title': 'Gold zakat calculator',
    'calc.crypto.title': 'Crypto calculator',
    'calc.savings.gold': 'Gold savings',
    'calc.savings.silver': 'Silver savings',
    'calc.weight': 'Weight (grams)',
    'calc.zakatWeight': 'Zakatable weight (grams)',
    'calc.karat': 'Karat',
    'calc.karatOption': 'Karat',
    'calc.priceType': 'Price type',
    'calc.sellPrice': 'Selling price',
    'calc.buyPrice': 'Buying price',
    'calc.currency': 'Currency',
    'calc.egp': 'Egyptian Pound',
    'calc.usd': 'US Dollar',
    'calc.result': 'Estimated value',
    'calc.zakatResult': 'Zakat amount',
    'calc.zakatUnit': 'EGP (2.5%)',
    'calc.coin': 'Coin',
    'calc.qty': 'Quantity',
    'calc.monthly': 'Monthly amount (EGP)',
    'calc.months': 'Duration (months)',
    'calc.savedTotal': 'Total saved amount',
    'calc.weightGold': 'Estimated gold weight',
    'calc.weightSilver': 'Estimated silver weight',
    'calc.gram': 'grams',
    'conv.from': 'From',
    'conv.to': 'To',
    'conv.swap': 'Swap currencies',
