/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurrenciesRouteImport } from './routes/currencies'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SilverRouteImport } from './routes/silver'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CryptoIndexRouteImport } from './routes/crypto.index'
import { Route as CryptoCoinRouteImport } from './routes/crypto.$coin'
import { Route as CurrencyCodeRouteImport } from './routes/currency.$code'
import { Route as GoldKaratRouteImport } from './routes/gold.$karat'
import { Route as ApiPublicCryptoPriceRouteImport } from './routes/api/public/crypto-price'
import { Route as ApiPublicCurrencyPriceRouteImport } from './routes/api/public/currency-price'
import { Route as ApiPublicGoldPriceRouteImport } from './routes/api/public/gold-price'
import { Route as ApiPublicNewsRouteImport } from './routes/api/public/news'
import { Route as ApiPublicSilverPriceRouteImport } from './routes/api/public/silver-price'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesRoute = CurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverRoute = SilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoIndexRoute = CryptoIndexRouteImport.update({
  id: '/crypto/',
  path: '/crypto/',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoCoinRoute = CryptoCoinRouteImport.update({
  id: '/crypto/$coin',
  path: '/crypto/$coin',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyCodeRoute = CurrencyCodeRouteImport.update({
  id: '/currency/$code',
  path: '/currency/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldKaratRoute = GoldKaratRouteImport.update({
  id: '/gold/$karat',
  path: '/gold/$karat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCryptoPriceRoute = ApiPublicCryptoPriceRouteImport.update({
  id: '/api/public/crypto-price',
  path: '/api/public/crypto-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCurrencyPriceRoute = ApiPublicCurrencyPriceRouteImport.update({
  id: '/api/public/currency-price',
  path: '/api/public/currency-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoldPriceRoute = ApiPublicGoldPriceRouteImport.update({
  id: '/api/public/gold-price',
  path: '/api/public/gold-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSilverPriceRoute = ApiPublicSilverPriceRouteImport.update({
  id: '/api/public/silver-price',
  path: '/api/public/silver-price',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/currencies': typeof CurrenciesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/silver': typeof SilverRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/crypto/$coin': typeof CryptoCoinRoute
  '/currency/$code': typeof CurrencyCodeRoute
  '/gold/$karat': typeof GoldKaratRoute
  '/blog/': typeof BlogIndexRoute
  '/crypto/': typeof CryptoIndexRoute
  '/api/public/crypto-price': typeof ApiPublicCryptoPriceRoute
  '/api/public/currency-price': typeof ApiPublicCurrencyPriceRoute
  '/api/public/gold-price': typeof ApiPublicGoldPriceRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/silver-price': typeof ApiPublicSilverPriceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/currencies': typeof CurrenciesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/silver': typeof SilverRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/crypto/$coin': typeof CryptoCoinRoute
  '/currency/$code': typeof CurrencyCodeRoute
  '/gold/$karat': typeof GoldKaratRoute
  '/blog': typeof BlogIndexRoute
  '/crypto': typeof CryptoIndexRoute
  '/api/public/crypto-price': typeof ApiPublicCryptoPriceRoute
  '/api/public/currency-price': typeof ApiPublicCurrencyPriceRoute
  '/api/public/gold-price': typeof ApiPublicGoldPriceRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/silver-price': typeof ApiPublicSilverPriceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/currencies': typeof CurrenciesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/silver': typeof SilverRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/crypto/$coin': typeof CryptoCoinRoute
  '/currency/$code': typeof CurrencyCodeRoute
  '/gold/$karat': typeof GoldKaratRoute
  '/blog/': typeof BlogIndexRoute
  '/crypto/': typeof CryptoIndexRoute
  '/api/public/crypto-price': typeof ApiPublicCryptoPriceRoute
  '/api/public/currency-price': typeof ApiPublicCurrencyPriceRoute
  '/api/public/gold-price': typeof ApiPublicGoldPriceRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/silver-price': typeof ApiPublicSilverPriceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/currencies'
    | '/disclaimer'
    | '/notifications'
    | '/privacy'
    | '/silver'
    | '/terms'
    | '/tools'
    | '/blog/$slug'
    | '/crypto/$coin'
    | '/currency/$code'
    | '/gold/$karat'
    | '/blog/'
    | '/crypto/'
    | '/api/public/crypto-price'
    | '/api/public/currency-price'
    | '/api/public/gold-price'
    | '/api/public/news'
    | '/api/public/silver-price'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/currencies'
    | '/disclaimer'
    | '/notifications'
    | '/privacy'
    | '/silver'
    | '/terms'
    | '/tools'
    | '/blog/$slug'
    | '/crypto/$coin'
    | '/currency/$code'
    | '/gold/$karat'
    | '/blog'
    | '/crypto'
    | '/api/public/crypto-price'
    | '/api/public/currency-price'
    | '/api/public/gold-price'
    | '/api/public/news'
    | '/api/public/silver-price'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/currencies'
    | '/disclaimer'
    | '/notifications'
    | '/privacy'
    | '/silver'
    | '/terms'
    | '/tools'
    | '/blog/$slug'
    | '/crypto/$coin'
    | '/currency/$code'
    | '/gold/$karat'
    | '/blog/'
    | '/crypto/'
    | '/api/public/crypto-price'
    | '/api/public/currency-price'
    | '/api/public/gold-price'
    | '/api/public/news'
    | '/api/public/silver-price'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CurrenciesRoute: typeof CurrenciesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SilverRoute: typeof SilverRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CryptoCoinRoute: typeof CryptoCoinRoute
  CurrencyCodeRoute: typeof CurrencyCodeRoute
  GoldKaratRoute: typeof GoldKaratRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CryptoIndexRoute: typeof CryptoIndexRoute
  ApiPublicCryptoPriceRoute: typeof ApiPublicCryptoPriceRoute
  ApiPublicCurrencyPriceRoute: typeof ApiPublicCurrencyPriceRoute
  ApiPublicGoldPriceRoute: typeof ApiPublicGoldPriceRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
  ApiPublicSilverPriceRoute: typeof ApiPublicSilverPriceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies': {
      id: '/currencies'
      path: '/currencies'
      fullPath: '/currencies'
      preLoaderRoute: typeof CurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver': {
      id: '/silver'
      path: '/silver'
      fullPath: '/silver'
      preLoaderRoute: typeof SilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/': {
      id: '/crypto/'
      path: '/crypto'
      fullPath: '/crypto/'
      preLoaderRoute: typeof CryptoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/$coin': {
      id: '/crypto/$coin'
      path: '/crypto/$coin'
      fullPath: '/crypto/$coin'
      preLoaderRoute: typeof CryptoCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency/$code': {
      id: '/currency/$code'
      path: '/currency/$code'
      fullPath: '/currency/$code'
      preLoaderRoute: typeof CurrencyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold/$karat': {
      id: '/gold/$karat'
      path: '/gold/$karat'
      fullPath: '/gold/$karat'
      preLoaderRoute: typeof GoldKaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crypto-price': {
      id: '/api/public/crypto-price'
      path: '/api/public/crypto-price'
      fullPath: '/api/public/crypto-price'
      preLoaderRoute: typeof ApiPublicCryptoPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/currency-price': {
      id: '/api/public/currency-price'
      path: '/api/public/currency-price'
      fullPath: '/api/public/currency-price'
      preLoaderRoute: typeof ApiPublicCurrencyPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gold-price': {
      id: '/api/public/gold-price'
      path: '/api/public/gold-price'
      fullPath: '/api/public/gold-price'
      preLoaderRoute: typeof ApiPublicGoldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/silver-price': {
      id: '/api/public/silver-price'
      path: '/api/public/silver-price'
      fullPath: '/api/public/silver-price'
      preLoaderRoute: typeof ApiPublicSilverPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CurrenciesRoute: CurrenciesRoute,
  DisclaimerRoute: DisclaimerRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SilverRoute: SilverRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CryptoCoinRoute: CryptoCoinRoute,
  CurrencyCodeRoute: CurrencyCodeRoute,
  GoldKaratRoute: GoldKaratRoute,
  BlogIndexRoute: BlogIndexRoute,
  CryptoIndexRoute: CryptoIndexRoute,
  ApiPublicCryptoPriceRoute: ApiPublicCryptoPriceRoute,
  ApiPublicCurrencyPriceRoute: ApiPublicCurrencyPriceRoute,
  ApiPublicGoldPriceRoute: ApiPublicGoldPriceRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
  ApiPublicSilverPriceRoute: ApiPublicSilverPriceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
